import type { HarnessConfiguration } from '../config/configuration.js'

/** Generates a trusted overlay from validated VS Code settings. */
export function renderOverlay(configuration: HarnessConfiguration): string {
  const thinking = configuration.reasoningEffort === 'off' ? 'disabled' : 'enabled'
  return `# Generated by DeepSeek Harness for VS Code. Manual edits are overwritten.\n\
- id: llm-deepseek\n\
  config:\n\
    thinking: ${thinking}\n\
    reasoningEffort: ${configuration.reasoningEffort}\n\
\n\
- id: agent-default-model\n\
  config:\n\
    provider: ${JSON.stringify(configuration.provider)}\n\
    model: ${configuration.model}\n\
\n\
- id: agent-presets\n\
  config:\n\
    default: ${configuration.agentPreset}\n\
\n\
- id: permission\n\
  config:\n\
    defaultPreset: ${configuration.permissionMode}\n`
}
